# Generated by Django 5.0.7 on 2024-07-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_alter_chatmembership_user_id_alter_message_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmembership',
            old_name='chatroom_id',
            new_name='chatroom',
        ),
        migrations.RenameField(
            model_name='chatmembership',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chatroom_id',
            new_name='chatroom',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(related_name='chatroom_id', to='chatapp.message'),
        ),
    ]
